excluded:
  - ${PWD}/Carthage
  - ${PWD}/Pods
  - ${PWD}/DerivedData
    

disabled_rules:
  - orphaned_doc_comment
  - switch_case_alignment
  - unused_capture_list
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - void_function_in_ternary # true? function() : function2()

analyzer_rules:
  - unused_import

cyclomatic_complexity:
  ignores_case_statements: true
  
opt_in_rules: # enable rules that is disabled by default
  - array_init
  - attributes
  - closure_end_indentation # Closure end should have the same indentation as the line that started it.
  - closure_spacing
  - collection_alignment
  - convenience_type # Types used for hosting only static members should be implemented as a caseless enum to avoid instantiation
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where # Prefer using .first(where:) over .filter { }.first in collections
  - last_where # Prefer using .last(where:) over .filter { }.last in collections
  - force_unwrapping # Force unwrapping should be avoided
  - implicitly_unwrapped_optional
  - indentation_width
  - literal_expression_end_indentation
  - multiline_arguments
#  - multiline_function_chains # Chained function calls should be either on the same line, or one per line
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords # Combine multiple pattern matching bindings by moving keywords out of tuples
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure # Trailing closure syntax should be used whenever possible
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition # The constant literal should be placed on the right-hand side of the comparison operator

attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@NSManaged"
    - "@IBAction"
    - "@objc"
  always_on_line_above:
    - "@IBInspectable"

function_body_length:
    warning: 60


type_name:
  allowed_symbols: "_" # so class can allow _ , useful for XCTest classes
  
identifier_name:
  allowed_symbols:
    "_" # used for converting structs to dictionary for using as params
  excluded: # excluded from warned about
    - i
    - a
    - x
    - id
    - vc
    - to

indentation_width:
  indentation_width: 4
  

line_length:
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true
  
private_over_fileprivate:
  validate_extensions: true

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 1

force_cast: error
force_try: error
force_unwrapping: error
legacy_hashing: error

custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
    severity: warning
